/**
 * Fixed, deterministic bot copy — used only for replies that must NOT depend on
 * a live LLM call (error fallbacks). Every other reply is generated by the model
 * in the customer's language. Mirrors the per-locale copy-map pattern in
 * `convex/emails/copy.ts`.
 */
import { WHATSAPP_LOCALE, type WhatsappLocale } from "../constants";

type BotCopy = {
	genericError: string;
};

const COPY: Record<WhatsappLocale, BotCopy> = {
	[WHATSAPP_LOCALE.EN]: {
		genericError:
			"Sorry — I ran into a problem answering that. Please try again in a moment, or contact the restaurant directly.",
	},
	[WHATSAPP_LOCALE.ES]: {
		genericError:
			"Lo siento, tuve un problema para responder. Inténtalo de nuevo en un momento o contacta directamente al restaurante.",
	},
};

/**
 * Pick a reply locale from the first candidate that looks like Spanish/English
 * (e.g. conversation locale → channel default → restaurant defaultLanguage),
 * defaulting to English.
 */
export function resolveLocale(...candidates: (string | null | undefined)[]): WhatsappLocale {
	for (const candidate of candidates) {
		const c = candidate?.toLowerCase();
		if (c?.startsWith("es")) return WHATSAPP_LOCALE.ES;
		if (c?.startsWith("en")) return WHATSAPP_LOCALE.EN;
	}
	return WHATSAPP_LOCALE.EN;
}

export function getBotCopy(locale: WhatsappLocale): BotCopy {
	return COPY[locale];
}
