#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Values live outside the repo: TWILIO_AUTH_TOKEN is a live credential and a
# repo-local .env is one `git add -A` away from being committed. 600 so only
# you can read it. Override with ENV_FILE=... if you keep secrets elsewhere.
ENV_FILE="${HOME}/.tavli/whatsapp-go-live.env"
mkdir -p "$(dirname "$ENV_FILE")"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

# Tavli's Convex deployments (README). `.convex.site` serves httpRouter routes;
# `.convex.cloud` serves functions. The webhook needs `.site`.
CONVEX_PROD_DEPLOYMENT="polite-antelope-545"
CONVEX_STAGING_DEPLOYMENT="aromatic-dog-762"
WHATSAPP_WEBHOOK_URL="https://${CONVEX_PROD_DEPLOYMENT}.convex.site/whatsapp/inbound"

# convex_prod_set KEY VALUE writes a Convex *deployment* env var on prod.
# These are NOT Infisical values: Infisical feeds the Dokploy container, and
# Convex functions never see it. See documentation/runbooks/stripe-go-live.md.
convex_prod_set() {
  local key="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("Convex prod env $key (no value captured)")
    warn "skipped $key: nothing captured"
    return
  fi
  if npx convex env set "$key" "$value" --prod >/dev/null 2>&1; then
    printf '  %s✓ set%s Convex prod env %s\n' "$GREEN" "$RESET" "$key"
  else
    SKIPPED+=("Convex prod env $key (run: npx convex env set $key <value> --prod)")
    warn "failed to set $key on prod; do it by hand later"
  fi
}

# probe_route DEPLOYMENT LABEL — 400 means the route is live and demanding a
# signature; 404 means the code isn't deployed there.
probe_route() {
  local code
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST --max-time 15 \
    "https://${1}.convex.site/whatsapp/inbound" || echo "000")
  case "$code" in
    400) printf '  %s✓%s %-8s route live (400 = missing signature, correct)\n' "$GREEN" "$RESET" "$2" ;;
    404) warn "$2: 404 — /whatsapp/inbound is NOT deployed there" ;;
    000) warn "$2: unreachable (network? deployment renamed?)" ;;
    *)   warn "$2: unexpected HTTP $code" ;;
  esac
}

TOTAL_STAGES=12

banner "Tavli WhatsApp go-live (TAVLI-90)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the assistant is actually deployed before you buy anything."
printf '\n'
probe_route "$CONVEX_PROD_DEPLOYMENT"    "prod"
probe_route "$CONVEX_STAGING_DEPLOYMENT" "staging"
printf '\n'
warn "Routing: a restaurant must be ENABLED or the assistant stays silent."
note "Per ADR-012, whatsappChannels.phoneNumber is retired. A row means 'this"
note "restaurant is enabled, with this short code'. Diners arrive through a"
note "wa.me deep link carrying a six-character code:"
note "    Hola, quiero informacion sobre Vernaculo . VRN-8F3"
note "A message with no code binds only if that phone talked to exactly one"
note "enabled restaurant in the last 30 days; otherwise it gets a fixed"
note "bilingual reply and no model call."
printf '\n'
note "Enabling is PLATFORM-ADMIN ONLY (whatsappChannels.setEnabled, gated like"
note "featureFlags.ts) because every enabled restaurant spends Tavli's own"
note "Twilio and OpenRouter money. Do it at /admin/whatsapp."
printf '\n'
say "Order note: Meta business verification gates SCALE, not launch. Twilio:"
note "  'you'll need to complete Meta business verification before you can"
note "   move into production' — unverified you still send, capped at 250"
note "   business-initiated messages / rolling 24h."
say "The assistant only REPLIES, and replies inside the 24h customer-service"
say "window don't count against that cap. So you can go live now and let"
say "verification (stages 11-12) run in the background."
printf '\n'
confirm "Understood — continue?" || { say "Stopping here. Re-run any time."; exit 0; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Meta: create the Tavli business portfolio"
say "A new portfolio is NOT nested under Perfect Genlabs. Business portfolios"
say "are independent top-level containers — separate assets, separate"
say "verification, separate admins. The only thing they share is you."
open_url "https://business.facebook.com/"
step "Click the portfolio switcher, top-left (the box reading 'Perfect Genlabs')."
step "At the BOTTOM of that panel: 'Crear un portafolio comercial'."
step "Legal name: Tavli's REGISTERED name, exactly as on the Constancia de"
step "  Situacion Fiscal — including the suffix (S.A. de C.V. / S. de R.L.)."
step "Website: https://tavliai.com"
printf '\n'
warn "Use the bare apex. www.tavliai.com does not resolve — Meta's check fails."
note "Editing legal name/address/website AFTER verification forces"
note "re-verification and another multi-day wait. Get it right now."
printf '\n'
warn "READ THIS BEFORE CREATING ANYTHING — learned 23 Aug 2026."
note "The first Tavli portfolio was RESTRICTED by Meta minutes after creation:"
note "  'Parece que esta cuenta se creo o uso con una automatizacion que no"
note "   cumple nuestras reglas.' A restricted portfolio is greyed out in"
note "  Twilio's popup ('not eligible for advertising') and cannot hold a WABA."
printf '\n'
note "Suspected trigger: a brand-new portfolio given 2FA, a phone, a WhatsApp"
note "number and a third-party OAuth grant within minutes looks scripted."
printf '\n'
step "So: create it, then STOP. Give it a Facebook Page and real business"
step "  details over the following days. Do the Twilio OAuth grant later,"
step "  not in the same sitting."
printf '\n'
warn "If it does get restricted: 'Solicitar revision' and wait. Do NOT create"
warn "another portfolio — the per-account cap is low and already reached here,"
warn "and evading a restriction escalates to the personal Facebook account"
warn "that administers everything."
note "Also: a portfolio belonging to someone else's company is not a fallback."
note "Verification would mean submitting their documents as proof of yours."
printf '\n'
ask META_PORTFOLIO_NAME "Legal name you entered:"
ask META_PORTFOLIO_ID   "Portfolio ID (Configuracion del negocio -> Info del negocio):"
write_env META_PORTFOLIO_NAME "$META_PORTFOLIO_NAME"
write_env META_PORTFOLIO_ID   "$META_PORTFOLIO_ID"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Meta: two-factor on the new portfolio"
say "Meta requires 2FA on the portfolio that hosts a WABA."
warn "Make sure the switcher shows TAVLI, not Perfect Genlabs, before you touch"
warn "these settings — they apply to whichever portfolio is selected."
open_url "https://business.facebook.com/settings/security"
step "Centro de seguridad -> Autenticacion en dos pasos -> 'Obligatoria para todos'."
note "If that link lands elsewhere: Configuracion del negocio -> Centro de seguridad."
printf '\n'
warn "Three different phone numbers live in this flow. Do not mix them up:"
note "  Informacion de contacto del PERFIL (celular / WhatsApp)"
note "    -> YOUR personal mobile. It receives the 2FA login code."
note "  Informacion del NEGOCIO (telefono + ubicacion principal)"
note "    -> the BUSINESS line + address. Verification matches these to the"
note "       document character for character, so set them before stage 11."
note "  The Twilio sender number"
note "    -> goes in at stage 6 ONLY. It never appears in Meta's settings."
printf '\n'
warn "Never put the Twilio number in the profile contact fields. Your 2FA code"
warn "would land somewhere you can only read via a console, and registering it"
warn "as a WhatsApp contact can disqualify it as a sender (stage 5's rule)."
printf '\n'
warn "Set the 2FA code delivery to an AUTHENTICATOR APP, not SMS."
note "'Controla como quieres recibir el codigo de inicio de sesion', bottom of"
note "Informacion del negocio. Meta's SMS to Mexican mobiles is unreliable —"
note "confirmed the hard way here. If the login code for the portfolio that"
note "owns your WABA depends on an SMS that never lands, you lock yourself"
note "out of the thing you just built. An authenticator has no delivery path."
pause "Press Enter once 2FA is on and the code goes to an authenticator."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Twilio: upgrade to a paid account"
say "Twilio prerequisite #1: 'Create and upgrade your Twilio account.'"
say "The Sandbox is explicitly testing-only and a trial can't hold a sender."
printf '\n'
warn "There are TWO Twilio accounts on this login. Same trap as the two Stripe"
warn "accounts in stripe-go-live.md: it all looks right until a call fails."
note "  tavli   ACbabb98...  <- upgraded. Use this one."
note "  gggfox  ACcb0a5e...  <- trial. Not this one."
step "Check the account picker top-left reads 'tavli' before going further."
printf '\n'
step "If it still shows Trial: add a payment method and upgrade."
open_url "https://console.twilio.com/us1/billing/manage-billing/billing-overview"
note "An upgraded account shows a balance and no trial banner."
printf '\n'
warn "Turn on auto-recharge while you are here (Billing overview)."
note "If the balance hits zero Twilio suspends messaging and the assistant goes"
note "silent — with nothing in the Convex logs to explain it."
pause "Press Enter once 'tavli' is confirmed upgraded."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Choose and pre-check the phone number"
say "Requirements: owned by Tavli, can receive an SMS or voice OTP, not behind"
say "an IVR, and — the one that trips people — NOT already registered on"
say "consumer WhatsApp or the WhatsApp Business app."
printf '\n'
warn "Country choice has a paperwork cost. Twilio's MX regulatory guidelines:"
note "  MX LOCAL  — needs a Regulatory Bundle: Constancia de Situacion Fiscal"
note "              + local address. The same document that gates Meta"
note "              verification, so it blocks you twice."
note "  MX MOBILE — unusable: 'Local carriers do not permit A2P or automated"
note "              messaging on this number type and such traffic will be"
note "              blocked immediately.'"
note "  US (+1)   — no bundle, ~\$1.15/mo, SMS-capable so it auto-verifies."
printf '\n'
say "WhatsApp does not care what country the sender is from. A +1 number gets"
say "you registered today; it just reads as less local to Mexican diners."
warn "Changing the sender number later means re-registering the WABA. Decide now."
printf '\n'
ask TWILIO_WHATSAPP_NUMBER "Number in E.164 (e.g. +5215512345678):"
_bare="${TWILIO_WHATSAPP_NUMBER#+}"
if [[ -n "$_bare" ]]; then
  step "Opening wa.me. If WhatsApp offers to CHAT with this number, it is"
  step "  already registered — delete that WhatsApp account first, or pick"
  step "  a different number."
  open_url "https://wa.me/${_bare}?text=hi"
  printf '\n'
  if ! confirm "Confirmed it is NOT on WhatsApp already?"; then
    say "Pick another number and re-run this stage."
    finish
    exit 0
  fi
fi
write_env TWILIO_WHATSAPP_NUMBER "$TWILIO_WHATSAPP_NUMBER"
note "A Twilio SMS-capable number verifies automatically — no OTP relay needed,"
note "which matters here: Meta's SMS to Mexican mobiles has already proven"
note "unreliable on this portfolio. If you use a non-Twilio number and the OTP"
note "never lands at stage 6, request the VOICE CALL option instead."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Twilio: WhatsApp self sign-up"
say "Meta's Embedded Signup popup, hosted inside the Twilio Console."
say "Completes in minutes — this is where you actually get a sender."
open_url "https://console.twilio.com/us1/develop/sms/senders/whatsapp-senders"
step "Messaging -> Senders -> WhatsApp senders -> 'Continue with Facebook'."
note "If that link redirects, navigate by hand — Twilio moves console URLs."
printf '\n'
warn "In the popup, select the TAVLI portfolio."
note "Do not let it attach the WABA to Perfect Genlabs or to a loose asset."
note "(No Tavli portfolio yet? You can create one right here in the popup.)"
printf '\n'
step "Create the WhatsApp Business Account."
step "Add ${TWILIO_WHATSAPP_NUMBER:-your number} and complete the OTP."
step "Display name: Tavli"
step "Set the mandatory two-step verification PIN."
printf '\n'
warn "Store that PIN in the password manager NOW. Twilio cannot recover it and"
warn "you need it to re-register the number anywhere else."
pause "Press Enter once the sender shows as registered."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Twilio: account SID and auth token"
say "The credentials Convex uses to send replies and verify inbound signatures."
open_url "https://console.twilio.com/"
step "On the Console dashboard home, find the 'Account Info' panel."
step "Copy the Account SID (starts AC)."
ask TWILIO_ACCOUNT_SID "Paste the Account SID:"
step "Reveal and copy the Auth Token on the same panel."
ask_secret TWILIO_AUTH_TOKEN "Paste the Auth Token (hidden):"
write_env TWILIO_ACCOUNT_SID "$TWILIO_ACCOUNT_SID"
write_env TWILIO_AUTH_TOKEN  "$TWILIO_AUTH_TOKEN"
TAVLI_SID_PREFIX="ACbabb98"
if [[ -n "${TWILIO_ACCOUNT_SID:-}" ]]; then
  if [[ "$TWILIO_ACCOUNT_SID" != AC* ]]; then
    warn "that does not start with 'AC' — an Account SID always does. Check it."
  elif [[ "$TWILIO_ACCOUNT_SID" == ACcb0a5e* ]]; then
    warn "STOP — that is the 'gggfox' trial account, not 'tavli'."
    warn "Switch accounts in the Console picker and re-run this stage."
  elif [[ "$TWILIO_ACCOUNT_SID" != ${TAVLI_SID_PREFIX}* ]]; then
    warn "expected the 'tavli' account (${TAVLI_SID_PREFIX}...) but got"
    warn "${TWILIO_ACCOUNT_SID:0:8}... — confirm which account you are in."
  else
    printf '  %s✓%s SID belongs to the tavli account\n' "$GREEN" "$RESET"
  fi
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Convex prod: set the environment variables"
say "Four values on the PRODUCTION deployment. Infisical does not reach Convex"
say "functions — this step is what makes the assistant work."
printf '\n'
note "Target: ${CONVEX_PROD_DEPLOYMENT}. Run from the repo root."
printf '\n'
warn "TWILIO_WEBHOOK_URL is missing from the TAVLI-90 checklist but the code"
warn "reads it — convex/whatsapp/twilioValidation.ts prefers it over the"
warn "request URL. Behind Traefik the reconstructed URL differs from the one"
warn "Twilio signed, so validation fails without it."
printf '\n'
if confirm "Set all four on ${CONVEX_PROD_DEPLOYMENT} now?"; then
  convex_prod_set TWILIO_ACCOUNT_SID     "${TWILIO_ACCOUNT_SID:-}"
  convex_prod_set TWILIO_AUTH_TOKEN      "${TWILIO_AUTH_TOKEN:-}"
  convex_prod_set TWILIO_WHATSAPP_NUMBER "${TWILIO_WHATSAPP_NUMBER:-}"
  convex_prod_set TWILIO_WEBHOOK_URL     "$WHATSAPP_WEBHOOK_URL"
else
  SKIPPED+=("Convex prod env vars (4) — values are in $ENV_FILE")
fi
printf '\n'
note "Also confirm OPENROUTER_API_KEY is set on prod — the assistant shares it"
note "with menu import, and without it every reply silently fails:"
note "  npx convex env get OPENROUTER_API_KEY --prod"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Twilio: point the inbound webhook at Convex"
open_url "https://console.twilio.com/us1/develop/sms/senders/whatsapp-senders"
step "Open the new sender -> its inbound webhook configuration."
step "Set 'When a message comes in' to POST:"
printf '\n      %s%s%s\n\n' "$BOLD" "$WHATSAPP_WEBHOOK_URL" "$RESET"
warn "Must match TWILIO_WEBHOOK_URL byte for byte — Twilio signs the exact URL"
warn "string. A trailing slash or http:// breaks signature validation."
pause "Press Enter once the webhook is saved."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Verify end to end — you are live after this"
say "Prove it before calling it done."
printf '\n'
step "From your own phone, WhatsApp ${TWILIO_WHATSAPP_NUMBER:-the new number}"
step "  and ask something about the menu."
note "No 'join <word>' any more — that was a Sandbox thing."
step "A reply means signature validation passed and the LLM turn ran."
printf '\n'
say "If nothing comes back, the logs name the failure directly:"
note "  npx convex logs --prod"
note "  '[whatsapp.validate] TWILIO_AUTH_TOKEN missing' -> stage 8 didn't land"
note "  403 Invalid signature                           -> URL mismatch, stage 9"
note "  '[whatsapp.outbound] ... missing'                -> SID/token/number unset"
printf '\n'
warn "No ENABLED restaurant = the fallback reply, even with everything above"
warn "correct. Enable one at /admin/whatsapp first, then test with its real"
warn "deep link — a bare 'hola' from an unknown phone is SUPPOSED to return"
warn "the fixed bilingual guidance."
printf '\n'
confirm "Got a reply?" || note "Fix it with the logs above, then re-run this stage."

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Meta: submit business verification"
say "You are already sending. This lifts the 250/24h cap and unlocks more than"
say "two senders. Meta says up to 14 business days; Twilio says weeks by region."
warn "Check the switcher reads TAVLI before you submit."
open_url "https://business.facebook.com/settings/security"
step "Open 'Centro de verificacion'."
step "Legal name, address and phone must match the document EXACTLY."
step "Website: https://tavliai.com"
printf '\n'
say "Upload ONE — Spanish is fine, no translation needed:"
note "  - Constancia de Situacion Fiscal (SAT)   <- easiest, name + address"
note "  - Acta constitutiva"
note "  - Business registration"
note "  - Corporate bank statement"
warn "A utility bill proves the ADDRESS only. It never proves the legal name."
printf '\n'
step "Connection check: code by email/SMS/WhatsApp, or domain verification via"
step "  a meta tag / DNS TXT record on tavliai.com (DNS is at Hostinger)."
pause "Press Enter once verification is submitted."

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Watch: verification result and display-name review"
say "Two background reviews. Nothing to do but check in — Ctrl-C and re-run"
say "this wizard later; everything captured is remembered."
printf '\n'
open_url "https://business.facebook.com/settings"
note "Verification status: Centro de verificacion -> Pendiente/Verificado/Rechazado."
note "Rejected is almost always a name mismatch by a word or a legal suffix."
printf '\n'
say "Display-name review fires automatically when the number becomes eligible"
say "for a higher tier — not now."
note "Cuentas de WhatsApp Business -> your WABA -> the number's display name"
note "shows Aprobado / Pendiente / Rechazado."
note "'Tavli' matches tavliai.com's branding, so it is approvable even though"
note "the verified legal name differs — Meta reviews the brand, not the deed."
warn "A rejected name caps business-initiated sends at 250/day and Meta may"
warn "disconnect the sender. Watch the phone_number_name_update webhook."
printf '\n'
note "Deliberately not here: message templates (TAVLI-90 step 8). The assistant"
note "only replies inside the 24h window, so it needs none yet."

finish
