/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesHistoryRouteImport } from './routes/sales-history'
import { Route as PurchaseHistoryRouteImport } from './routes/purchase-history'
import { Route as PendingMaterialsRouteImport } from './routes/pending-materials'
import { Route as MyActiveBidsRouteImport } from './routes/my-active-bids'
import { Route as LiveRfqsRouteImport } from './routes/live-rfqs'
import { Route as LiveAuctionsRouteImport } from './routes/live-auctions'
import { Route as EShopRouteImport } from './routes/e-shop'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesHistoryLiveRouteImport } from './routes/sales-history/live'
import { Route as LiveRfqsCreateRouteImport } from './routes/live-rfqs/create'
import { Route as AlertsCreatePriceRouteImport } from './routes/alerts/create-price'
import { Route as AlertsCreateMaterialRouteImport } from './routes/alerts/create-material'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMaterialsRouteImport } from './routes/admin/materials'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSigninRouteImport } from './routes/api/auth/signin'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SalesHistoryRoute = SalesHistoryRouteImport.update({
  id: '/sales-history',
  path: '/sales-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseHistoryRoute = PurchaseHistoryRouteImport.update({
  id: '/purchase-history',
  path: '/purchase-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingMaterialsRoute = PendingMaterialsRouteImport.update({
  id: '/pending-materials',
  path: '/pending-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const MyActiveBidsRoute = MyActiveBidsRouteImport.update({
  id: '/my-active-bids',
  path: '/my-active-bids',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRfqsRoute = LiveRfqsRouteImport.update({
  id: '/live-rfqs',
  path: '/live-rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveAuctionsRoute = LiveAuctionsRouteImport.update({
  id: '/live-auctions',
  path: '/live-auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const EShopRoute = EShopRouteImport.update({
  id: '/e-shop',
  path: '/e-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesHistoryLiveRoute = SalesHistoryLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => SalesHistoryRoute,
} as any)
const LiveRfqsCreateRoute = LiveRfqsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LiveRfqsRoute,
} as any)
const AlertsCreatePriceRoute = AlertsCreatePriceRouteImport.update({
  id: '/create-price',
  path: '/create-price',
  getParentRoute: () => AlertsRoute,
} as any)
const AlertsCreateMaterialRoute = AlertsCreateMaterialRouteImport.update({
  id: '/create-material',
  path: '/create-material',
  getParentRoute: () => AlertsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/e-shop': typeof EShopRoute
  '/live-auctions': typeof LiveAuctionsRoute
  '/live-rfqs': typeof LiveRfqsRouteWithChildren
  '/my-active-bids': typeof MyActiveBidsRoute
  '/pending-materials': typeof PendingMaterialsRoute
  '/purchase-history': typeof PurchaseHistoryRoute
  '/sales-history': typeof SalesHistoryRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/alerts/create-material': typeof AlertsCreateMaterialRoute
  '/alerts/create-price': typeof AlertsCreatePriceRoute
  '/live-rfqs/create': typeof LiveRfqsCreateRoute
  '/sales-history/live': typeof SalesHistoryLiveRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/e-shop': typeof EShopRoute
  '/live-auctions': typeof LiveAuctionsRoute
  '/live-rfqs': typeof LiveRfqsRouteWithChildren
  '/my-active-bids': typeof MyActiveBidsRoute
  '/pending-materials': typeof PendingMaterialsRoute
  '/purchase-history': typeof PurchaseHistoryRoute
  '/sales-history': typeof SalesHistoryRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/alerts/create-material': typeof AlertsCreateMaterialRoute
  '/alerts/create-price': typeof AlertsCreatePriceRoute
  '/live-rfqs/create': typeof LiveRfqsCreateRoute
  '/sales-history/live': typeof SalesHistoryLiveRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/e-shop': typeof EShopRoute
  '/live-auctions': typeof LiveAuctionsRoute
  '/live-rfqs': typeof LiveRfqsRouteWithChildren
  '/my-active-bids': typeof MyActiveBidsRoute
  '/pending-materials': typeof PendingMaterialsRoute
  '/purchase-history': typeof PurchaseHistoryRoute
  '/sales-history': typeof SalesHistoryRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/alerts/create-material': typeof AlertsCreateMaterialRoute
  '/alerts/create-price': typeof AlertsCreatePriceRoute
  '/live-rfqs/create': typeof LiveRfqsCreateRoute
  '/sales-history/live': typeof SalesHistoryLiveRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/e-shop'
    | '/live-auctions'
    | '/live-rfqs'
    | '/my-active-bids'
    | '/pending-materials'
    | '/purchase-history'
    | '/sales-history'
    | '/admin/materials'
    | '/admin/users'
    | '/alerts/create-material'
    | '/alerts/create-price'
    | '/live-rfqs/create'
    | '/sales-history/live'
    | '/api/auth/callback'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/e-shop'
    | '/live-auctions'
    | '/live-rfqs'
    | '/my-active-bids'
    | '/pending-materials'
    | '/purchase-history'
    | '/sales-history'
    | '/admin/materials'
    | '/admin/users'
    | '/alerts/create-material'
    | '/alerts/create-price'
    | '/live-rfqs/create'
    | '/sales-history/live'
    | '/api/auth/callback'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/e-shop'
    | '/live-auctions'
    | '/live-rfqs'
    | '/my-active-bids'
    | '/pending-materials'
    | '/purchase-history'
    | '/sales-history'
    | '/admin/materials'
    | '/admin/users'
    | '/alerts/create-material'
    | '/alerts/create-price'
    | '/live-rfqs/create'
    | '/sales-history/live'
    | '/api/auth/callback'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  EShopRoute: typeof EShopRoute
  LiveAuctionsRoute: typeof LiveAuctionsRoute
  LiveRfqsRoute: typeof LiveRfqsRouteWithChildren
  MyActiveBidsRoute: typeof MyActiveBidsRoute
  PendingMaterialsRoute: typeof PendingMaterialsRoute
  PurchaseHistoryRoute: typeof PurchaseHistoryRoute
  SalesHistoryRoute: typeof SalesHistoryRouteWithChildren
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-history': {
      id: '/sales-history'
      path: '/sales-history'
      fullPath: '/sales-history'
      preLoaderRoute: typeof SalesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-history': {
      id: '/purchase-history'
      path: '/purchase-history'
      fullPath: '/purchase-history'
      preLoaderRoute: typeof PurchaseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-materials': {
      id: '/pending-materials'
      path: '/pending-materials'
      fullPath: '/pending-materials'
      preLoaderRoute: typeof PendingMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-active-bids': {
      id: '/my-active-bids'
      path: '/my-active-bids'
      fullPath: '/my-active-bids'
      preLoaderRoute: typeof MyActiveBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-rfqs': {
      id: '/live-rfqs'
      path: '/live-rfqs'
      fullPath: '/live-rfqs'
      preLoaderRoute: typeof LiveRfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-auctions': {
      id: '/live-auctions'
      path: '/live-auctions'
      fullPath: '/live-auctions'
      preLoaderRoute: typeof LiveAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-shop': {
      id: '/e-shop'
      path: '/e-shop'
      fullPath: '/e-shop'
      preLoaderRoute: typeof EShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-history/live': {
      id: '/sales-history/live'
      path: '/live'
      fullPath: '/sales-history/live'
      preLoaderRoute: typeof SalesHistoryLiveRouteImport
      parentRoute: typeof SalesHistoryRoute
    }
    '/live-rfqs/create': {
      id: '/live-rfqs/create'
      path: '/create'
      fullPath: '/live-rfqs/create'
      preLoaderRoute: typeof LiveRfqsCreateRouteImport
      parentRoute: typeof LiveRfqsRoute
    }
    '/alerts/create-price': {
      id: '/alerts/create-price'
      path: '/create-price'
      fullPath: '/alerts/create-price'
      preLoaderRoute: typeof AlertsCreatePriceRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/alerts/create-material': {
      id: '/alerts/create-material'
      path: '/create-material'
      fullPath: '/alerts/create-material'
      preLoaderRoute: typeof AlertsCreateMaterialRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlertsRouteChildren {
  AlertsCreateMaterialRoute: typeof AlertsCreateMaterialRoute
  AlertsCreatePriceRoute: typeof AlertsCreatePriceRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsCreateMaterialRoute: AlertsCreateMaterialRoute,
  AlertsCreatePriceRoute: AlertsCreatePriceRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface LiveRfqsRouteChildren {
  LiveRfqsCreateRoute: typeof LiveRfqsCreateRoute
}

const LiveRfqsRouteChildren: LiveRfqsRouteChildren = {
  LiveRfqsCreateRoute: LiveRfqsCreateRoute,
}

const LiveRfqsRouteWithChildren = LiveRfqsRoute._addFileChildren(
  LiveRfqsRouteChildren,
)

interface SalesHistoryRouteChildren {
  SalesHistoryLiveRoute: typeof SalesHistoryLiveRoute
}

const SalesHistoryRouteChildren: SalesHistoryRouteChildren = {
  SalesHistoryLiveRoute: SalesHistoryLiveRoute,
}

const SalesHistoryRouteWithChildren = SalesHistoryRoute._addFileChildren(
  SalesHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  EShopRoute: EShopRoute,
  LiveAuctionsRoute: LiveAuctionsRoute,
  LiveRfqsRoute: LiveRfqsRouteWithChildren,
  MyActiveBidsRoute: MyActiveBidsRoute,
  PendingMaterialsRoute: PendingMaterialsRoute,
  PurchaseHistoryRoute: PurchaseHistoryRoute,
  SalesHistoryRoute: SalesHistoryRouteWithChildren,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
