/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRestaurantsRouteImport } from './routes/admin/restaurants'
import { Route as AdminRestaurantRouteImport } from './routes/admin/restaurant'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminOptionsRouteImport } from './routes/admin/options'
import { Route as AdminMenusIndexRouteImport } from './routes/admin/menus/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminRestaurantTablesRouteImport } from './routes/admin/restaurant/tables'
import { Route as AdminMenusMenuIdRouteImport } from './routes/admin/menus/$menuId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as RSlugTTableNumberRouteImport } from './routes/r/$slug/t/$tableNumber'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as RSlugTTableNumberMenuRouteImport } from './routes/r/$slug/t/$tableNumber/menu'
import { Route as RSlugTTableNumberLangRouteImport } from './routes/r/$slug/t/$tableNumber/$lang'
import { Route as RSlugTTableNumberLangMenuRouteImport } from './routes/r/$slug/t/$tableNumber/$lang/menu'
import { Route as RSlugTTableNumberLangCartRouteImport } from './routes/r/$slug/t/$tableNumber/$lang/cart'
import { Route as RSlugTTableNumberLangOrderOrderIdRouteImport } from './routes/r/$slug/t/$tableNumber/$lang/order/$orderId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantRoute = AdminRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOptionsRoute = AdminOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusIndexRoute = AdminMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantTablesRoute = AdminRestaurantTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRestaurantRoute,
} as any)
const AdminMenusMenuIdRoute = AdminMenusMenuIdRouteImport.update({
  id: '/menus/$menuId',
  path: '/menus/$menuId',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugTTableNumberRoute = RSlugTTableNumberRouteImport.update({
  id: '/r/$slug/t/$tableNumber',
  path: '/r/$slug/t/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugTTableNumberMenuRoute = RSlugTTableNumberMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RSlugTTableNumberRoute,
} as any)
const RSlugTTableNumberLangRoute = RSlugTTableNumberLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => RSlugTTableNumberRoute,
} as any)
const RSlugTTableNumberLangMenuRoute =
  RSlugTTableNumberLangMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => RSlugTTableNumberLangRoute,
  } as any)
const RSlugTTableNumberLangCartRoute =
  RSlugTTableNumberLangCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => RSlugTTableNumberLangRoute,
  } as any)
const RSlugTTableNumberLangOrderOrderIdRoute =
  RSlugTTableNumberLangOrderOrderIdRouteImport.update({
    id: '/order/$orderId',
    path: '/order/$orderId',
    getParentRoute: () => RSlugTTableNumberLangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/options': typeof AdminOptionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/restaurant': typeof AdminRestaurantRouteWithChildren
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/restaurant/tables': typeof AdminRestaurantTablesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/r/$slug/t/$tableNumber': typeof RSlugTTableNumberRouteWithChildren
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/r/$slug/t/$tableNumber/$lang': typeof RSlugTTableNumberLangRouteWithChildren
  '/r/$slug/t/$tableNumber/menu': typeof RSlugTTableNumberMenuRoute
  '/r/$slug/t/$tableNumber/$lang/cart': typeof RSlugTTableNumberLangCartRoute
  '/r/$slug/t/$tableNumber/$lang/menu': typeof RSlugTTableNumberLangMenuRoute
  '/r/$slug/t/$tableNumber/$lang/order/$orderId': typeof RSlugTTableNumberLangOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/options': typeof AdminOptionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/restaurant': typeof AdminRestaurantRouteWithChildren
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/restaurant/tables': typeof AdminRestaurantTablesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/r/$slug/t/$tableNumber': typeof RSlugTTableNumberRouteWithChildren
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/r/$slug/t/$tableNumber/$lang': typeof RSlugTTableNumberLangRouteWithChildren
  '/r/$slug/t/$tableNumber/menu': typeof RSlugTTableNumberMenuRoute
  '/r/$slug/t/$tableNumber/$lang/cart': typeof RSlugTTableNumberLangCartRoute
  '/r/$slug/t/$tableNumber/$lang/menu': typeof RSlugTTableNumberLangMenuRoute
  '/r/$slug/t/$tableNumber/$lang/order/$orderId': typeof RSlugTTableNumberLangOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/options': typeof AdminOptionsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/restaurant': typeof AdminRestaurantRouteWithChildren
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/restaurant/tables': typeof AdminRestaurantTablesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/menus/': typeof AdminMenusIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/r/$slug/t/$tableNumber': typeof RSlugTTableNumberRouteWithChildren
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/r/$slug/t/$tableNumber/$lang': typeof RSlugTTableNumberLangRouteWithChildren
  '/r/$slug/t/$tableNumber/menu': typeof RSlugTTableNumberMenuRoute
  '/r/$slug/t/$tableNumber/$lang/cart': typeof RSlugTTableNumberLangCartRoute
  '/r/$slug/t/$tableNumber/$lang/menu': typeof RSlugTTableNumberLangMenuRoute
  '/r/$slug/t/$tableNumber/$lang/order/$orderId': typeof RSlugTTableNumberLangOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/options'
    | '/admin/orders'
    | '/admin/restaurant'
    | '/admin/restaurants'
    | '/admin/users'
    | '/admin/menus/$menuId'
    | '/admin/restaurant/tables'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/menus'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/r/$slug/t/$tableNumber'
    | '/demo/start/ssr'
    | '/r/$slug/t/$tableNumber/$lang'
    | '/r/$slug/t/$tableNumber/menu'
    | '/r/$slug/t/$tableNumber/$lang/cart'
    | '/r/$slug/t/$tableNumber/$lang/menu'
    | '/r/$slug/t/$tableNumber/$lang/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/options'
    | '/admin/orders'
    | '/admin/restaurant'
    | '/admin/restaurants'
    | '/admin/users'
    | '/admin/menus/$menuId'
    | '/admin/restaurant/tables'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/menus'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/r/$slug/t/$tableNumber'
    | '/demo/start/ssr'
    | '/r/$slug/t/$tableNumber/$lang'
    | '/r/$slug/t/$tableNumber/menu'
    | '/r/$slug/t/$tableNumber/$lang/cart'
    | '/r/$slug/t/$tableNumber/$lang/menu'
    | '/r/$slug/t/$tableNumber/$lang/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/options'
    | '/admin/orders'
    | '/admin/restaurant'
    | '/admin/restaurants'
    | '/admin/users'
    | '/admin/menus/$menuId'
    | '/admin/restaurant/tables'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/menus/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/r/$slug/t/$tableNumber'
    | '/demo/start/ssr/'
    | '/r/$slug/t/$tableNumber/$lang'
    | '/r/$slug/t/$tableNumber/menu'
    | '/r/$slug/t/$tableNumber/$lang/cart'
    | '/r/$slug/t/$tableNumber/$lang/menu'
    | '/r/$slug/t/$tableNumber/$lang/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  RSlugTTableNumberRoute: typeof RSlugTTableNumberRouteWithChildren
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurant': {
      id: '/admin/restaurant'
      path: '/restaurant'
      fullPath: '/admin/restaurant'
      preLoaderRoute: typeof AdminRestaurantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/options': {
      id: '/admin/options'
      path: '/options'
      fullPath: '/admin/options'
      preLoaderRoute: typeof AdminOptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus/': {
      id: '/admin/menus/'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurant/tables': {
      id: '/admin/restaurant/tables'
      path: '/tables'
      fullPath: '/admin/restaurant/tables'
      preLoaderRoute: typeof AdminRestaurantTablesRouteImport
      parentRoute: typeof AdminRestaurantRoute
    }
    '/admin/menus/$menuId': {
      id: '/admin/menus/$menuId'
      path: '/menus/$menuId'
      fullPath: '/admin/menus/$menuId'
      preLoaderRoute: typeof AdminMenusMenuIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/t/$tableNumber': {
      id: '/r/$slug/t/$tableNumber'
      path: '/r/$slug/t/$tableNumber'
      fullPath: '/r/$slug/t/$tableNumber'
      preLoaderRoute: typeof RSlugTTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/t/$tableNumber/menu': {
      id: '/r/$slug/t/$tableNumber/menu'
      path: '/menu'
      fullPath: '/r/$slug/t/$tableNumber/menu'
      preLoaderRoute: typeof RSlugTTableNumberMenuRouteImport
      parentRoute: typeof RSlugTTableNumberRoute
    }
    '/r/$slug/t/$tableNumber/$lang': {
      id: '/r/$slug/t/$tableNumber/$lang'
      path: '/$lang'
      fullPath: '/r/$slug/t/$tableNumber/$lang'
      preLoaderRoute: typeof RSlugTTableNumberLangRouteImport
      parentRoute: typeof RSlugTTableNumberRoute
    }
    '/r/$slug/t/$tableNumber/$lang/menu': {
      id: '/r/$slug/t/$tableNumber/$lang/menu'
      path: '/menu'
      fullPath: '/r/$slug/t/$tableNumber/$lang/menu'
      preLoaderRoute: typeof RSlugTTableNumberLangMenuRouteImport
      parentRoute: typeof RSlugTTableNumberLangRoute
    }
    '/r/$slug/t/$tableNumber/$lang/cart': {
      id: '/r/$slug/t/$tableNumber/$lang/cart'
      path: '/cart'
      fullPath: '/r/$slug/t/$tableNumber/$lang/cart'
      preLoaderRoute: typeof RSlugTTableNumberLangCartRouteImport
      parentRoute: typeof RSlugTTableNumberLangRoute
    }
    '/r/$slug/t/$tableNumber/$lang/order/$orderId': {
      id: '/r/$slug/t/$tableNumber/$lang/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/r/$slug/t/$tableNumber/$lang/order/$orderId'
      preLoaderRoute: typeof RSlugTTableNumberLangOrderOrderIdRouteImport
      parentRoute: typeof RSlugTTableNumberLangRoute
    }
  }
}

interface AdminRestaurantRouteChildren {
  AdminRestaurantTablesRoute: typeof AdminRestaurantTablesRoute
}

const AdminRestaurantRouteChildren: AdminRestaurantRouteChildren = {
  AdminRestaurantTablesRoute: AdminRestaurantTablesRoute,
}

const AdminRestaurantRouteWithChildren = AdminRestaurantRoute._addFileChildren(
  AdminRestaurantRouteChildren,
)

interface AdminRouteChildren {
  AdminOptionsRoute: typeof AdminOptionsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminRestaurantRoute: typeof AdminRestaurantRouteWithChildren
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminMenusMenuIdRoute: typeof AdminMenusMenuIdRoute
  AdminMenusIndexRoute: typeof AdminMenusIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOptionsRoute: AdminOptionsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminRestaurantRoute: AdminRestaurantRouteWithChildren,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminMenusMenuIdRoute: AdminMenusMenuIdRoute,
  AdminMenusIndexRoute: AdminMenusIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RSlugTTableNumberLangRouteChildren {
  RSlugTTableNumberLangCartRoute: typeof RSlugTTableNumberLangCartRoute
  RSlugTTableNumberLangMenuRoute: typeof RSlugTTableNumberLangMenuRoute
  RSlugTTableNumberLangOrderOrderIdRoute: typeof RSlugTTableNumberLangOrderOrderIdRoute
}

const RSlugTTableNumberLangRouteChildren: RSlugTTableNumberLangRouteChildren = {
  RSlugTTableNumberLangCartRoute: RSlugTTableNumberLangCartRoute,
  RSlugTTableNumberLangMenuRoute: RSlugTTableNumberLangMenuRoute,
  RSlugTTableNumberLangOrderOrderIdRoute:
    RSlugTTableNumberLangOrderOrderIdRoute,
}

const RSlugTTableNumberLangRouteWithChildren =
  RSlugTTableNumberLangRoute._addFileChildren(
    RSlugTTableNumberLangRouteChildren,
  )

interface RSlugTTableNumberRouteChildren {
  RSlugTTableNumberLangRoute: typeof RSlugTTableNumberLangRouteWithChildren
  RSlugTTableNumberMenuRoute: typeof RSlugTTableNumberMenuRoute
}

const RSlugTTableNumberRouteChildren: RSlugTTableNumberRouteChildren = {
  RSlugTTableNumberLangRoute: RSlugTTableNumberLangRouteWithChildren,
  RSlugTTableNumberMenuRoute: RSlugTTableNumberMenuRoute,
}

const RSlugTTableNumberRouteWithChildren =
  RSlugTTableNumberRoute._addFileChildren(RSlugTTableNumberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  RSlugTTableNumberRoute: RSlugTTableNumberRouteWithChildren,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
