/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as StorefrontRouteImport } from './routes/storefront'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRestaurantsRouteImport } from './routes/admin/restaurants'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminReservationsIndexRouteImport } from './routes/admin/reservations/index'
import { Route as AdminMenusIndexRouteImport } from './routes/admin/menus/index'
import { Route as RSlugReserveRouteImport } from './routes/r/$slug/reserve'
import { Route as RSlugOrdersRouteImport } from './routes/r/$slug/orders'
import { Route as RSlugMenuRouteImport } from './routes/r/$slug/menu'
import { Route as RSlugLangRouteImport } from './routes/r/$slug/$lang'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminReservationsSettingsRouteImport } from './routes/admin/reservations/settings'
import { Route as AdminReservationsLocksRouteImport } from './routes/admin/reservations/locks'
import { Route as AdminMenusMenuIdRouteImport } from './routes/admin/menus/$menuId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as RSlugOrderOrderIdRouteImport } from './routes/r/$slug/order/$orderId'
import { Route as RSlugLangOrdersRouteImport } from './routes/r/$slug/$lang/orders'
import { Route as RSlugLangMenuRouteImport } from './routes/r/$slug/$lang/menu'
import { Route as RSlugLangCheckoutRouteImport } from './routes/r/$slug/$lang/checkout'
import { Route as RSlugLangCartRouteImport } from './routes/r/$slug/$lang/cart'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as RSlugLangOrderOrderIdRouteImport } from './routes/r/$slug/$lang/order/$orderId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRoute = StorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsIndexRoute = AdminReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusIndexRoute = AdminMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AdminRoute,
} as any)
const RSlugReserveRoute = RSlugReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugOrdersRoute = RSlugOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugMenuRoute = RSlugMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugLangRoute = RSlugLangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => RSlugRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservationsSettingsRoute =
  AdminReservationsSettingsRouteImport.update({
    id: '/reservations/settings',
    path: '/reservations/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminReservationsLocksRoute = AdminReservationsLocksRouteImport.update({
  id: '/reservations/locks',
  path: '/reservations/locks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenusMenuIdRoute = AdminMenusMenuIdRouteImport.update({
  id: '/menus/$menuId',
  path: '/menus/$menuId',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugOrderOrderIdRoute = RSlugOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugLangOrdersRoute = RSlugLangOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => RSlugLangRoute,
} as any)
const RSlugLangMenuRoute = RSlugLangMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RSlugLangRoute,
} as any)
const RSlugLangCheckoutRoute = RSlugLangCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => RSlugLangRoute,
} as any)
const RSlugLangCartRoute = RSlugLangCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => RSlugLangRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugLangOrderOrderIdRoute = RSlugLangOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => RSlugLangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/storefront': typeof StorefrontRoute
  '/success': typeof SuccessRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/reservations/locks': typeof AdminReservationsLocksRoute
  '/admin/reservations/settings': typeof AdminReservationsSettingsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/r/$slug/$lang': typeof RSlugLangRouteWithChildren
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/orders': typeof RSlugOrdersRoute
  '/r/$slug/reserve': typeof RSlugReserveRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/admin/reservations': typeof AdminReservationsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/r/$slug/$lang/cart': typeof RSlugLangCartRoute
  '/r/$slug/$lang/checkout': typeof RSlugLangCheckoutRoute
  '/r/$slug/$lang/menu': typeof RSlugLangMenuRoute
  '/r/$slug/$lang/orders': typeof RSlugLangOrdersRoute
  '/r/$slug/order/$orderId': typeof RSlugOrderOrderIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/r/$slug/$lang/order/$orderId': typeof RSlugLangOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/storefront': typeof StorefrontRoute
  '/success': typeof SuccessRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/reservations/locks': typeof AdminReservationsLocksRoute
  '/admin/reservations/settings': typeof AdminReservationsSettingsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/r/$slug/$lang': typeof RSlugLangRouteWithChildren
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/orders': typeof RSlugOrdersRoute
  '/r/$slug/reserve': typeof RSlugReserveRoute
  '/admin/menus': typeof AdminMenusIndexRoute
  '/admin/reservations': typeof AdminReservationsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/r/$slug/$lang/cart': typeof RSlugLangCartRoute
  '/r/$slug/$lang/checkout': typeof RSlugLangCheckoutRoute
  '/r/$slug/$lang/menu': typeof RSlugLangMenuRoute
  '/r/$slug/$lang/orders': typeof RSlugLangOrdersRoute
  '/r/$slug/order/$orderId': typeof RSlugOrderOrderIdRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/r/$slug/$lang/order/$orderId': typeof RSlugLangOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/storefront': typeof StorefrontRoute
  '/success': typeof SuccessRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/users': typeof AdminUsersRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/menus/$menuId': typeof AdminMenusMenuIdRoute
  '/admin/reservations/locks': typeof AdminReservationsLocksRoute
  '/admin/reservations/settings': typeof AdminReservationsSettingsRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/r/$slug/$lang': typeof RSlugLangRouteWithChildren
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/orders': typeof RSlugOrdersRoute
  '/r/$slug/reserve': typeof RSlugReserveRoute
  '/admin/menus/': typeof AdminMenusIndexRoute
  '/admin/reservations/': typeof AdminReservationsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/r/$slug/$lang/cart': typeof RSlugLangCartRoute
  '/r/$slug/$lang/checkout': typeof RSlugLangCheckoutRoute
  '/r/$slug/$lang/menu': typeof RSlugLangMenuRoute
  '/r/$slug/$lang/orders': typeof RSlugLangOrdersRoute
  '/r/$slug/order/$orderId': typeof RSlugOrderOrderIdRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/r/$slug/$lang/order/$orderId': typeof RSlugLangOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/storefront'
    | '/success'
    | '/admin/orders'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/restaurants'
    | '/admin/users'
    | '/r/$slug'
    | '/admin/menus/$menuId'
    | '/admin/reservations/locks'
    | '/admin/reservations/settings'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/r/$slug/$lang'
    | '/r/$slug/menu'
    | '/r/$slug/orders'
    | '/r/$slug/reserve'
    | '/admin/menus'
    | '/admin/reservations'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/r/$slug/$lang/cart'
    | '/r/$slug/$lang/checkout'
    | '/r/$slug/$lang/menu'
    | '/r/$slug/$lang/orders'
    | '/r/$slug/order/$orderId'
    | '/demo/start/ssr'
    | '/r/$slug/$lang/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/storefront'
    | '/success'
    | '/admin/orders'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/restaurants'
    | '/admin/users'
    | '/r/$slug'
    | '/admin/menus/$menuId'
    | '/admin/reservations/locks'
    | '/admin/reservations/settings'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/r/$slug/$lang'
    | '/r/$slug/menu'
    | '/r/$slug/orders'
    | '/r/$slug/reserve'
    | '/admin/menus'
    | '/admin/reservations'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/r/$slug/$lang/cart'
    | '/r/$slug/$lang/checkout'
    | '/r/$slug/$lang/menu'
    | '/r/$slug/$lang/orders'
    | '/r/$slug/order/$orderId'
    | '/demo/start/ssr'
    | '/r/$slug/$lang/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/storefront'
    | '/success'
    | '/admin/orders'
    | '/admin/organizations'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/restaurants'
    | '/admin/users'
    | '/r/$slug'
    | '/admin/menus/$menuId'
    | '/admin/reservations/locks'
    | '/admin/reservations/settings'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/r/$slug/$lang'
    | '/r/$slug/menu'
    | '/r/$slug/orders'
    | '/r/$slug/reserve'
    | '/admin/menus/'
    | '/admin/reservations/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/r/$slug/$lang/cart'
    | '/r/$slug/$lang/checkout'
    | '/r/$slug/$lang/menu'
    | '/r/$slug/$lang/orders'
    | '/r/$slug/order/$orderId'
    | '/demo/start/ssr/'
    | '/r/$slug/$lang/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StorefrontRoute: typeof StorefrontRoute
  SuccessRoute: typeof SuccessRoute
  RSlugRoute: typeof RSlugRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront': {
      id: '/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations/': {
      id: '/admin/reservations/'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus/': {
      id: '/admin/menus/'
      path: '/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$slug/reserve': {
      id: '/r/$slug/reserve'
      path: '/reserve'
      fullPath: '/r/$slug/reserve'
      preLoaderRoute: typeof RSlugReserveRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/orders': {
      id: '/r/$slug/orders'
      path: '/orders'
      fullPath: '/r/$slug/orders'
      preLoaderRoute: typeof RSlugOrdersRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/menu': {
      id: '/r/$slug/menu'
      path: '/menu'
      fullPath: '/r/$slug/menu'
      preLoaderRoute: typeof RSlugMenuRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/$lang': {
      id: '/r/$slug/$lang'
      path: '/$lang'
      fullPath: '/r/$slug/$lang'
      preLoaderRoute: typeof RSlugLangRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservations/settings': {
      id: '/admin/reservations/settings'
      path: '/reservations/settings'
      fullPath: '/admin/reservations/settings'
      preLoaderRoute: typeof AdminReservationsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations/locks': {
      id: '/admin/reservations/locks'
      path: '/reservations/locks'
      fullPath: '/admin/reservations/locks'
      preLoaderRoute: typeof AdminReservationsLocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menus/$menuId': {
      id: '/admin/menus/$menuId'
      path: '/menus/$menuId'
      fullPath: '/admin/menus/$menuId'
      preLoaderRoute: typeof AdminMenusMenuIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/order/$orderId': {
      id: '/r/$slug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/r/$slug/order/$orderId'
      preLoaderRoute: typeof RSlugOrderOrderIdRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/$lang/orders': {
      id: '/r/$slug/$lang/orders'
      path: '/orders'
      fullPath: '/r/$slug/$lang/orders'
      preLoaderRoute: typeof RSlugLangOrdersRouteImport
      parentRoute: typeof RSlugLangRoute
    }
    '/r/$slug/$lang/menu': {
      id: '/r/$slug/$lang/menu'
      path: '/menu'
      fullPath: '/r/$slug/$lang/menu'
      preLoaderRoute: typeof RSlugLangMenuRouteImport
      parentRoute: typeof RSlugLangRoute
    }
    '/r/$slug/$lang/checkout': {
      id: '/r/$slug/$lang/checkout'
      path: '/checkout'
      fullPath: '/r/$slug/$lang/checkout'
      preLoaderRoute: typeof RSlugLangCheckoutRouteImport
      parentRoute: typeof RSlugLangRoute
    }
    '/r/$slug/$lang/cart': {
      id: '/r/$slug/$lang/cart'
      path: '/cart'
      fullPath: '/r/$slug/$lang/cart'
      preLoaderRoute: typeof RSlugLangCartRouteImport
      parentRoute: typeof RSlugLangRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug/$lang/order/$orderId': {
      id: '/r/$slug/$lang/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/r/$slug/$lang/order/$orderId'
      preLoaderRoute: typeof RSlugLangOrderOrderIdRouteImport
      parentRoute: typeof RSlugLangRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminMenusMenuIdRoute: typeof AdminMenusMenuIdRoute
  AdminReservationsLocksRoute: typeof AdminReservationsLocksRoute
  AdminReservationsSettingsRoute: typeof AdminReservationsSettingsRoute
  AdminMenusIndexRoute: typeof AdminMenusIndexRoute
  AdminReservationsIndexRoute: typeof AdminReservationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminMenusMenuIdRoute: AdminMenusMenuIdRoute,
  AdminReservationsLocksRoute: AdminReservationsLocksRoute,
  AdminReservationsSettingsRoute: AdminReservationsSettingsRoute,
  AdminMenusIndexRoute: AdminMenusIndexRoute,
  AdminReservationsIndexRoute: AdminReservationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RSlugLangRouteChildren {
  RSlugLangCartRoute: typeof RSlugLangCartRoute
  RSlugLangCheckoutRoute: typeof RSlugLangCheckoutRoute
  RSlugLangMenuRoute: typeof RSlugLangMenuRoute
  RSlugLangOrdersRoute: typeof RSlugLangOrdersRoute
  RSlugLangOrderOrderIdRoute: typeof RSlugLangOrderOrderIdRoute
}

const RSlugLangRouteChildren: RSlugLangRouteChildren = {
  RSlugLangCartRoute: RSlugLangCartRoute,
  RSlugLangCheckoutRoute: RSlugLangCheckoutRoute,
  RSlugLangMenuRoute: RSlugLangMenuRoute,
  RSlugLangOrdersRoute: RSlugLangOrdersRoute,
  RSlugLangOrderOrderIdRoute: RSlugLangOrderOrderIdRoute,
}

const RSlugLangRouteWithChildren = RSlugLangRoute._addFileChildren(
  RSlugLangRouteChildren,
)

interface RSlugRouteChildren {
  RSlugLangRoute: typeof RSlugLangRouteWithChildren
  RSlugMenuRoute: typeof RSlugMenuRoute
  RSlugOrdersRoute: typeof RSlugOrdersRoute
  RSlugReserveRoute: typeof RSlugReserveRoute
  RSlugOrderOrderIdRoute: typeof RSlugOrderOrderIdRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugLangRoute: RSlugLangRouteWithChildren,
  RSlugMenuRoute: RSlugMenuRoute,
  RSlugOrdersRoute: RSlugOrdersRoute,
  RSlugReserveRoute: RSlugReserveRoute,
  RSlugOrderOrderIdRoute: RSlugOrderOrderIdRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StorefrontRoute: StorefrontRoute,
  SuccessRoute: SuccessRoute,
  RSlugRoute: RSlugRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
